### ISSUE TITLE
Resolution issue with PXE boot on newer 2021 Dell Model (5420/5520

### ISSUE THREAD

**Issue by petedoc1972** [MSEndpointMgr/ConfigMgrOSDFrontEnd#8]
Screen Resolution  on these model is very low  such that OSD Frontend does fit into the screen, can't be moved so that one can progress through the menus. Boot to USB is fine only occurs during PXE.  Request to allow for custom resolution of Frontend to be included in xml as a way to bypass this issue

**Comment by hkystar35** [comment]
You're thinking this is related to the Dell models? Hmmm. We saw this show up on the 5420, too. What led you suspect it being OSDFrontEnd? From my view, the background image was also distorted so I didn't see it as a an OSDFE issue.

**Comment by petedoc1972** [comment]
Not exactly an OSD Front End issue , but since you cannot adjust the resolution of OSD front end you cannot use PXE with these models (can't see the buttons to click next), have to revert to USB boot...

**Comment by hkystar35** [comment]
I just found this comment from yesterday, looks like it's a BIOS issue and a fix is coming

> ‎04-15-2021 11:26 AM
Re: Latitude 5420 and display resolution when booting from WinPE image (SCCM deployment)
I think it's okay to say, without breaking the NDA, that the test version we got from  our Dell rep does indeed fix the video issues during UEFI / PXE booting.  We're sticking to the latest production release though, and just having our techs go through our task sequence UDI wizard mostly blind, hitting Alt-F on the last page to finish (since they can't see the buttons).
They did say the official fix would be released towards the end of this month (April 2021) so hopefully we see that soon.  Once they do though, it's still kind of a problem because we'll have to modify our task sequence to update the BIOS first during WinPE, and then boot back into the TS for the rest of the interactive stuff.  Normally we do a BIOS update as the very last step of the process when it's running in the full Windows OS, since that seemed to be the safest option, and we're doing a reboot there anyway, but I guess I'll have to change things up.
Eventually we'll get fixed BIOS versions on the factory delivered machines, but I have a feeling that won't be the case until much later this year once their inventory with old BIOS versions is depleted and they start making new systems with the fixed BIOS and get those into the supply chain.  Even then, you never know if you'll get an old-stock system that still needs the update.

https://www.dell.com/community/Latitude/Latitude-5420-and-display-resolution-when-booting-from-WinPE/m-p/7854842/highlight/true#M32304

**Comment by petedoc1972** [comment]
Thanks for the update!

**Comment by hkystar35** [comment]
@petedoc1972 
1.5.2 released yesterday. Tested in our environment and it fixes the display issue.
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=111dm&oscode=wt64a&productcode=latitude-5420-laptop

**Comment by petedoc1972** [comment]
Thanks! works here too!
